name:                great-filter
version:             0.0.1
github:              "amcknight/great-filter"
license:             BSD3
author:              "Andrew McKnight"
maintainer:          "thedonk@gmail.com"
copyright:           "2020 Andrew McKnight"

extra-source-files:
- README.md
- ChangeLog.md

description:         Please see the README on GitHub at <https://github.com/amcknight/great-filter#readme>
dependencies:
- base >= 4.7 && < 5
- monad-bayes

library:
  source-dirs: src

executables:
  great-filter-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - great-filter

tests:
  great-filter-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - great-filter
